#!/bin/bash

# Create the directory if it doesn't exist
mkdir -p /tmp/u

# Move files beginning with an uppercase letter to /tmp/u
find . -maxdepth 1 -type f -name '[[:upper:]]*' -exec mv {} /tmp/u \;
